/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  type QueryContext,
  useQueryContext,
  queryKeyFn,
} from "./query-context";
import { deepMerge } from "./query-utils";
import type * as Fetcher from "./query-fetcher";
import { queryFetch } from "./query-fetcher";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type PostAuthSignupError = Fetcher.ErrorWrapper<{
  status: 500;
  payload: {
    /**
     * @default false
     */
    success?: boolean;
    message: string;
  };
}>;

export type PostAuthSignupResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    /**
     * @format uuid
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    id: string;
    fullName: string;
    /**
     * @format email
     * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
     */
    email: string;
    /**
     * @format uri
     */
    image?: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
     */
    createdAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
     */
    updatedAt: string;
  };
};

export type PostAuthSignupRequestBody = {
  /**
   * @minLength 2
   * @maxLength 40
   */
  fullName: string;
  /**
   * @format uri
   */
  image?: string;
  /**
   * @format email
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  /**
   * @minLength 8
   */
  password: string;
};

export type PostAuthSignupVariables = {
  body: PostAuthSignupRequestBody;
} & QueryContext["fetcherOptions"];

/**
 * Register a user
 */
export const fetchPostAuthSignup = (
  variables: PostAuthSignupVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    PostAuthSignupResponse,
    PostAuthSignupError,
    PostAuthSignupRequestBody,
    {},
    {},
    {}
  >({ url: "/auth/signup", method: "post", ...variables, signal });

/**
 * Register a user
 */
export const usePostAuthSignup = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      PostAuthSignupResponse,
      PostAuthSignupError,
      PostAuthSignupVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueryContext();
  return reactQuery.useMutation<
    PostAuthSignupResponse,
    PostAuthSignupError,
    PostAuthSignupVariables
  >({
    mutationFn: (variables: PostAuthSignupVariables) =>
      fetchPostAuthSignup(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type PostAuthLoginError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 401;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 403;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 500;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
>;

export type PostAuthLoginResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    /**
     * @format uuid
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    id: string;
    fullName: string;
    role: "user" | "admin";
    /**
     * @format email
     * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
     */
    email: string;
    /**
     * @format uri
     */
    image?: string;
  };
};

export type PostAuthLoginRequestBody = {
  /**
   * @format email
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  password: string;
};

export type PostAuthLoginVariables = {
  body: PostAuthLoginRequestBody;
} & QueryContext["fetcherOptions"];

/**
 * Login with email and password
 */
export const fetchPostAuthLogin = (
  variables: PostAuthLoginVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    PostAuthLoginResponse,
    PostAuthLoginError,
    PostAuthLoginRequestBody,
    {},
    {},
    {}
  >({ url: "/auth/login", method: "post", ...variables, signal });

/**
 * Login with email and password
 */
export const usePostAuthLogin = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      PostAuthLoginResponse,
      PostAuthLoginError,
      PostAuthLoginVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueryContext();
  return reactQuery.useMutation<
    PostAuthLoginResponse,
    PostAuthLoginError,
    PostAuthLoginVariables
  >({
    mutationFn: (variables: PostAuthLoginVariables) =>
      fetchPostAuthLogin(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type PostAuthLogoutError = Fetcher.ErrorWrapper<{
  status: 500;
  payload: {
    /**
     * @default false
     */
    success?: boolean;
    message: string;
  };
}>;

export type PostAuthLogoutVariables = QueryContext["fetcherOptions"];

/**
 * Logout from your session
 */
export const fetchPostAuthLogout = (
  variables: PostAuthLogoutVariables,
  signal?: AbortSignal,
) =>
  queryFetch<undefined, PostAuthLogoutError, undefined, {}, {}, {}>({
    url: "/auth/logout",
    method: "post",
    ...variables,
    signal,
  });

/**
 * Logout from your session
 */
export const usePostAuthLogout = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      undefined,
      PostAuthLogoutError,
      PostAuthLogoutVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueryContext();
  return reactQuery.useMutation<
    undefined,
    PostAuthLogoutError,
    PostAuthLogoutVariables
  >({
    mutationFn: (variables: PostAuthLogoutVariables) =>
      fetchPostAuthLogout(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GetAuthSessionError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 401;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 403;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 500;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
>;

export type GetAuthSessionResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    /**
     * @format uuid
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    id: string;
    fullName: string;
    role: "user" | "admin";
    /**
     * @format email
     * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
     */
    email: string;
    /**
     * @format uri
     */
    image?: string;
  };
};

export type GetAuthSessionVariables = QueryContext["fetcherOptions"];

/**
 * Get current session user
 */
export const fetchGetAuthSession = (
  variables: GetAuthSessionVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    GetAuthSessionResponse,
    GetAuthSessionError,
    undefined,
    {},
    {},
    {}
  >({ url: "/auth/session", method: "get", ...variables, signal });

/**
 * Get current session user
 */
export function getAuthSessionQuery(variables: GetAuthSessionVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<GetAuthSessionResponse>;
};

export function getAuthSessionQuery(
  variables: GetAuthSessionVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<GetAuthSessionResponse>)
    | reactQuery.SkipToken;
};

export function getAuthSessionQuery(
  variables: GetAuthSessionVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/auth/session",
      operationId: "getAuthSession",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGetAuthSession(variables, signal),
  };
}

/**
 * Get current session user
 */
export const useSuspenseGetAuthSession = <TData = GetAuthSessionResponse,>(
  variables: GetAuthSessionVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetAuthSessionResponse,
      GetAuthSessionError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useSuspenseQuery<
    GetAuthSessionResponse,
    GetAuthSessionError,
    TData
  >({
    ...getAuthSessionQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get current session user
 */
export const useGetAuthSession = <TData = GetAuthSessionResponse,>(
  variables: GetAuthSessionVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetAuthSessionResponse,
      GetAuthSessionError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useQuery<
    GetAuthSessionResponse,
    GetAuthSessionError,
    TData
  >({
    ...getAuthSessionQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type PostPropertiesError = Fetcher.ErrorWrapper<undefined>;

export type PostPropertiesResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    /**
     * @minLength 3
     * @maxLength 255
     */
    title: string;
    /**
     * @minLength 10
     */
    description: string;
    price: number;
    /**
     * @minLength 2
     * @maxLength 3
     */
    currency: string;
    area?: number;
    /**
     * @minLength 3
     */
    address: string;
    /**
     * @minLength 2
     */
    city: string;
    /**
     * @minLength 2
     */
    country: string;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    bedroom?: number;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    kitchen?: number;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    bathroom?: number;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    livingroom?: number;
    /**
     * @format uri
     */
    coverImage: string;
    images?: string[];
  };
};

export type PostPropertiesRequestBody = {
  /**
   * @minLength 3
   * @maxLength 255
   */
  title: string;
  /**
   * @minLength 10
   */
  description: string;
  price: number;
  /**
   * @minLength 2
   * @maxLength 3
   */
  currency: string;
  area?: number;
  /**
   * @minLength 3
   */
  address: string;
  /**
   * @minLength 2
   */
  city: string;
  /**
   * @minLength 2
   */
  country: string;
  /**
   * @default 0
   * @minimum 0
   * @maximum 9007199254740991
   */
  bedroom?: number;
  /**
   * @default 0
   * @minimum 0
   * @maximum 9007199254740991
   */
  kitchen?: number;
  /**
   * @default 0
   * @minimum 0
   * @maximum 9007199254740991
   */
  bathroom?: number;
  /**
   * @default 0
   * @minimum 0
   * @maximum 9007199254740991
   */
  livingroom?: number;
  /**
   * @format uri
   */
  coverImage: string;
  images?: string[];
};

export type PostPropertiesVariables = {
  body: PostPropertiesRequestBody;
} & QueryContext["fetcherOptions"];

/**
 * Register a property
 */
export const fetchPostProperties = (
  variables: PostPropertiesVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    PostPropertiesResponse,
    PostPropertiesError,
    PostPropertiesRequestBody,
    {},
    {},
    {}
  >({ url: "/properties", method: "post", ...variables, signal });

/**
 * Register a property
 */
export const usePostProperties = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      PostPropertiesResponse,
      PostPropertiesError,
      PostPropertiesVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueryContext();
  return reactQuery.useMutation<
    PostPropertiesResponse,
    PostPropertiesError,
    PostPropertiesVariables
  >({
    mutationFn: (variables: PostPropertiesVariables) =>
      fetchPostProperties(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GetPropertiesQueryParams = {
  /**
   * @default 1
   * @exclusiveMinimum 0
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @default 10
   * @exclusiveMinimum 0
   * @maximum 9007199254740991
   */
  limit?: number;
  /**
   * @exclusiveMinimum 0
   */
  minPrice?: number;
  /**
   * @exclusiveMinimum 0
   */
  maxPrice?: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  bedroom?: number;
  search?: string;
};

export type GetPropertiesError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 401;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 403;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 500;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
>;

export type GetPropertiesResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    properties: {
      /**
       * @minLength 3
       * @maxLength 255
       */
      title: string;
      /**
       * @minLength 10
       */
      description: string;
      price: number;
      /**
       * @minLength 2
       * @maxLength 3
       */
      currency: string;
      area?: number;
      /**
       * @minLength 3
       */
      address: string;
      /**
       * @minLength 2
       */
      city: string;
      /**
       * @minLength 2
       */
      country: string;
      /**
       * @default 0
       * @minimum 0
       * @maximum 9007199254740991
       */
      bedroom?: number;
      /**
       * @default 0
       * @minimum 0
       * @maximum 9007199254740991
       */
      kitchen?: number;
      /**
       * @default 0
       * @minimum 0
       * @maximum 9007199254740991
       */
      bathroom?: number;
      /**
       * @default 0
       * @minimum 0
       * @maximum 9007199254740991
       */
      livingroom?: number;
      /**
       * @format uri
       */
      coverImage: string;
      images?: string[];
      /**
       * @format uuid
       * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
       */
      id: string;
      /**
       * @default 0
       */
      favouriteCount?: number;
      /**
       * @format date-time
       * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
       */
      listedAt: string;
      /**
       * @format date-time
       * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
       */
      updatedAt: string;
      isFavourited: boolean;
    }[];
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
};

export type GetPropertiesVariables = {
  queryParams?: GetPropertiesQueryParams;
} & QueryContext["fetcherOptions"];

/**
 * Get list of properties
 */
export const fetchGetProperties = (
  variables: GetPropertiesVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    GetPropertiesResponse,
    GetPropertiesError,
    undefined,
    {},
    GetPropertiesQueryParams,
    {}
  >({ url: "/properties", method: "get", ...variables, signal });

/**
 * Get list of properties
 */
export function getPropertiesQuery(variables: GetPropertiesVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<GetPropertiesResponse>;
};

export function getPropertiesQuery(
  variables: GetPropertiesVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<GetPropertiesResponse>)
    | reactQuery.SkipToken;
};

export function getPropertiesQuery(
  variables: GetPropertiesVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/properties",
      operationId: "getProperties",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetProperties(variables, signal),
  };
}

/**
 * Get list of properties
 */
export const useSuspenseGetProperties = <TData = GetPropertiesResponse,>(
  variables: GetPropertiesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesResponse,
      GetPropertiesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useSuspenseQuery<
    GetPropertiesResponse,
    GetPropertiesError,
    TData
  >({
    ...getPropertiesQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get list of properties
 */
export const useGetProperties = <TData = GetPropertiesResponse,>(
  variables: GetPropertiesVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesResponse,
      GetPropertiesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useQuery<GetPropertiesResponse, GetPropertiesError, TData>({
    ...getPropertiesQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type GetPropertiesFavouritesQueryParams = {
  /**
   * @default 1
   * @exclusiveMinimum 0
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * @default 10
   * @exclusiveMinimum 0
   * @maximum 9007199254740991
   */
  limit?: number;
  /**
   * @exclusiveMinimum 0
   */
  minPrice?: number;
  /**
   * @exclusiveMinimum 0
   */
  maxPrice?: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  bedroom?: number;
  search?: string;
};

export type GetPropertiesFavouritesError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 401;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 403;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 500;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
>;

export type GetPropertiesFavouritesResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    favourites: {
      /**
       * @format uuid
       * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
       */
      id: string;
      /**
       * @format date
       * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
       */
      favouritedAt: string;
      property: {
        /**
         * @minLength 3
         * @maxLength 255
         */
        title: string;
        /**
         * @minLength 10
         */
        description: string;
        price: number;
        /**
         * @minLength 2
         * @maxLength 3
         */
        currency: string;
        area?: number;
        /**
         * @minLength 3
         */
        address: string;
        /**
         * @minLength 2
         */
        city: string;
        /**
         * @minLength 2
         */
        country: string;
        /**
         * @default 0
         * @minimum 0
         * @maximum 9007199254740991
         */
        bedroom?: number;
        /**
         * @default 0
         * @minimum 0
         * @maximum 9007199254740991
         */
        kitchen?: number;
        /**
         * @default 0
         * @minimum 0
         * @maximum 9007199254740991
         */
        bathroom?: number;
        /**
         * @default 0
         * @minimum 0
         * @maximum 9007199254740991
         */
        livingroom?: number;
        /**
         * @format uri
         */
        coverImage: string;
        images?: string[];
        /**
         * @format uuid
         * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
         */
        id: string;
        /**
         * @default 0
         */
        favouriteCount?: number;
        /**
         * @format date-time
         * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
         */
        listedAt: string;
        /**
         * @format date-time
         * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
         */
        updatedAt: string;
        isFavourited: boolean;
      };
    }[];
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
};

export type GetPropertiesFavouritesVariables = {
  queryParams?: GetPropertiesFavouritesQueryParams;
} & QueryContext["fetcherOptions"];

/**
 * Get list of favourite properties
 */
export const fetchGetPropertiesFavourites = (
  variables: GetPropertiesFavouritesVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    GetPropertiesFavouritesResponse,
    GetPropertiesFavouritesError,
    undefined,
    {},
    GetPropertiesFavouritesQueryParams,
    {}
  >({ url: "/properties/favourites", method: "get", ...variables, signal });

/**
 * Get list of favourite properties
 */
export function getPropertiesFavouritesQuery(
  variables: GetPropertiesFavouritesVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (
    options: QueryFnOptions,
  ) => Promise<GetPropertiesFavouritesResponse>;
};

export function getPropertiesFavouritesQuery(
  variables: GetPropertiesFavouritesVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<GetPropertiesFavouritesResponse>)
    | reactQuery.SkipToken;
};

export function getPropertiesFavouritesQuery(
  variables: GetPropertiesFavouritesVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/properties/favourites",
      operationId: "getPropertiesFavourites",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGetPropertiesFavourites(variables, signal),
  };
}

/**
 * Get list of favourite properties
 */
export const useSuspenseGetPropertiesFavourites = <
  TData = GetPropertiesFavouritesResponse,
>(
  variables: GetPropertiesFavouritesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesFavouritesResponse,
      GetPropertiesFavouritesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useSuspenseQuery<
    GetPropertiesFavouritesResponse,
    GetPropertiesFavouritesError,
    TData
  >({
    ...getPropertiesFavouritesQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get list of favourite properties
 */
export const useGetPropertiesFavourites = <
  TData = GetPropertiesFavouritesResponse,
>(
  variables: GetPropertiesFavouritesVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesFavouritesResponse,
      GetPropertiesFavouritesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useQuery<
    GetPropertiesFavouritesResponse,
    GetPropertiesFavouritesError,
    TData
  >({
    ...getPropertiesFavouritesQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type PostPropertiesFavouritesByPropertyIdPathParams = {
  propertyId: string;
};

export type PostPropertiesFavouritesByPropertyIdError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 401;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 403;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 500;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
>;

export type PostPropertiesFavouritesByPropertyIdResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    /**
     * @format uuid
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    propertyId: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
     */
    favouritedAt: string;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    favouriteCount: number;
  };
};

export type PostPropertiesFavouritesByPropertyIdVariables = {
  pathParams: PostPropertiesFavouritesByPropertyIdPathParams;
} & QueryContext["fetcherOptions"];

/**
 * Add property to favourites
 */
export const fetchPostPropertiesFavouritesByPropertyId = (
  variables: PostPropertiesFavouritesByPropertyIdVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    PostPropertiesFavouritesByPropertyIdResponse,
    PostPropertiesFavouritesByPropertyIdError,
    undefined,
    {},
    {},
    PostPropertiesFavouritesByPropertyIdPathParams
  >({
    url: "/properties/favourites/{propertyId}",
    method: "post",
    ...variables,
    signal,
  });

/**
 * Add property to favourites
 */
export const usePostPropertiesFavouritesByPropertyId = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      PostPropertiesFavouritesByPropertyIdResponse,
      PostPropertiesFavouritesByPropertyIdError,
      PostPropertiesFavouritesByPropertyIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueryContext();
  return reactQuery.useMutation<
    PostPropertiesFavouritesByPropertyIdResponse,
    PostPropertiesFavouritesByPropertyIdError,
    PostPropertiesFavouritesByPropertyIdVariables
  >({
    mutationFn: (variables: PostPropertiesFavouritesByPropertyIdVariables) =>
      fetchPostPropertiesFavouritesByPropertyId(
        deepMerge(fetcherOptions, variables),
      ),
    ...options,
  });
};

export type DeletePropertiesFavouritesByPropertyIdPathParams = {
  propertyId: string;
};

export type DeletePropertiesFavouritesByPropertyIdError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 401;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 403;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 500;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
>;

export type DeletePropertiesFavouritesByPropertyIdResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    /**
     * @format uuid
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    propertyId: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
     */
    favouritedAt: string;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    favouriteCount: number;
  };
};

export type DeletePropertiesFavouritesByPropertyIdVariables = {
  pathParams: DeletePropertiesFavouritesByPropertyIdPathParams;
} & QueryContext["fetcherOptions"];

/**
 * Remove property to favourites
 */
export const fetchDeletePropertiesFavouritesByPropertyId = (
  variables: DeletePropertiesFavouritesByPropertyIdVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    DeletePropertiesFavouritesByPropertyIdResponse,
    DeletePropertiesFavouritesByPropertyIdError,
    undefined,
    {},
    {},
    DeletePropertiesFavouritesByPropertyIdPathParams
  >({
    url: "/properties/favourites/{propertyId}",
    method: "delete",
    ...variables,
    signal,
  });

/**
 * Remove property to favourites
 */
export const useDeletePropertiesFavouritesByPropertyId = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      DeletePropertiesFavouritesByPropertyIdResponse,
      DeletePropertiesFavouritesByPropertyIdError,
      DeletePropertiesFavouritesByPropertyIdVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueryContext();
  return reactQuery.useMutation<
    DeletePropertiesFavouritesByPropertyIdResponse,
    DeletePropertiesFavouritesByPropertyIdError,
    DeletePropertiesFavouritesByPropertyIdVariables
  >({
    mutationFn: (variables: DeletePropertiesFavouritesByPropertyIdVariables) =>
      fetchDeletePropertiesFavouritesByPropertyId(
        deepMerge(fetcherOptions, variables),
      ),
    ...options,
  });
};

export type GetPropertiesByPropertyIdPathParams = {
  propertyId: string;
};

export type GetPropertiesByPropertyIdError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 401;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 403;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
  | {
      status: 500;
      payload: {
        /**
         * @default false
         */
        success?: boolean;
        message: string;
      };
    }
>;

export type GetPropertiesByPropertyIdResponse = {
  /**
   * @default true
   */
  success?: boolean;
  message: string;
  data: {
    /**
     * @minLength 3
     * @maxLength 255
     */
    title: string;
    /**
     * @minLength 10
     */
    description: string;
    price: number;
    /**
     * @minLength 2
     * @maxLength 3
     */
    currency: string;
    area?: number;
    /**
     * @minLength 3
     */
    address: string;
    /**
     * @minLength 2
     */
    city: string;
    /**
     * @minLength 2
     */
    country: string;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    bedroom?: number;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    kitchen?: number;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    bathroom?: number;
    /**
     * @default 0
     * @minimum 0
     * @maximum 9007199254740991
     */
    livingroom?: number;
    /**
     * @format uri
     */
    coverImage: string;
    images?: string[];
    /**
     * @format uuid
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    id: string;
    /**
     * @default 0
     */
    favouriteCount?: number;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
     */
    listedAt: string;
    /**
     * @format date-time
     * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$
     */
    updatedAt: string;
    isFavourited: boolean;
  };
};

export type GetPropertiesByPropertyIdVariables = {
  pathParams: GetPropertiesByPropertyIdPathParams;
} & QueryContext["fetcherOptions"];

/**
 * Get property by ID
 */
export const fetchGetPropertiesByPropertyId = (
  variables: GetPropertiesByPropertyIdVariables,
  signal?: AbortSignal,
) =>
  queryFetch<
    GetPropertiesByPropertyIdResponse,
    GetPropertiesByPropertyIdError,
    undefined,
    {},
    {},
    GetPropertiesByPropertyIdPathParams
  >({ url: "/properties/{propertyId}", method: "get", ...variables, signal });

/**
 * Get property by ID
 */
export function getPropertiesByPropertyIdQuery(
  variables: GetPropertiesByPropertyIdVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (
    options: QueryFnOptions,
  ) => Promise<GetPropertiesByPropertyIdResponse>;
};

export function getPropertiesByPropertyIdQuery(
  variables: GetPropertiesByPropertyIdVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<GetPropertiesByPropertyIdResponse>)
    | reactQuery.SkipToken;
};

export function getPropertiesByPropertyIdQuery(
  variables: GetPropertiesByPropertyIdVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/properties/{propertyId}",
      operationId: "getPropertiesByPropertyId",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGetPropertiesByPropertyId(variables, signal),
  };
}

/**
 * Get property by ID
 */
export const useSuspenseGetPropertiesByPropertyId = <
  TData = GetPropertiesByPropertyIdResponse,
>(
  variables: GetPropertiesByPropertyIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesByPropertyIdResponse,
      GetPropertiesByPropertyIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useSuspenseQuery<
    GetPropertiesByPropertyIdResponse,
    GetPropertiesByPropertyIdError,
    TData
  >({
    ...getPropertiesByPropertyIdQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get property by ID
 */
export const useGetPropertiesByPropertyId = <
  TData = GetPropertiesByPropertyIdResponse,
>(
  variables: GetPropertiesByPropertyIdVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesByPropertyIdResponse,
      GetPropertiesByPropertyIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueryContext(options);
  return reactQuery.useQuery<
    GetPropertiesByPropertyIdResponse,
    GetPropertiesByPropertyIdError,
    TData
  >({
    ...getPropertiesByPropertyIdQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type QueryOperation =
  | {
      path: "/auth/session";
      operationId: "getAuthSession";
      variables: GetAuthSessionVariables | reactQuery.SkipToken;
    }
  | {
      path: "/properties";
      operationId: "getProperties";
      variables: GetPropertiesVariables | reactQuery.SkipToken;
    }
  | {
      path: "/properties/favourites";
      operationId: "getPropertiesFavourites";
      variables: GetPropertiesFavouritesVariables | reactQuery.SkipToken;
    }
  | {
      path: "/properties/{propertyId}";
      operationId: "getPropertiesByPropertyId";
      variables: GetPropertiesByPropertyIdVariables | reactQuery.SkipToken;
    };
