/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutProtectedRouteImport } from './routes/_layout/_protected'
import { Route as LayoutPropertyIdRouteImport } from './routes/_layout/$propertyId'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as LayoutProtectedFavouritesRouteImport } from './routes/_layout/_protected/favourites'
import { Route as LayoutAdminAdminRouteImport } from './routes/_layout/_admin/admin'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedRoute = LayoutProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPropertyIdRoute = LayoutPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProtectedFavouritesRoute =
  LayoutProtectedFavouritesRouteImport.update({
    id: '/favourites',
    path: '/favourites',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)
const LayoutAdminAdminRoute = LayoutAdminAdminRouteImport.update({
  id: '/_admin/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$propertyId': typeof LayoutPropertyIdRoute
  '/admin': typeof LayoutAdminAdminRoute
  '/favourites': typeof LayoutProtectedFavouritesRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$propertyId': typeof LayoutPropertyIdRoute
  '/': typeof LayoutIndexRoute
  '/admin': typeof LayoutAdminAdminRoute
  '/favourites': typeof LayoutProtectedFavouritesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_layout/$propertyId': typeof LayoutPropertyIdRoute
  '/_layout/_protected': typeof LayoutProtectedRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_admin/admin': typeof LayoutAdminAdminRoute
  '/_layout/_protected/favourites': typeof LayoutProtectedFavouritesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/$propertyId'
    | '/admin'
    | '/favourites'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/$propertyId' | '/' | '/admin' | '/favourites'
  id:
    | '__root__'
    | '/_layout'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_layout/$propertyId'
    | '/_layout/_protected'
    | '/_layout/'
    | '/_layout/_admin/admin'
    | '/_layout/_protected/favourites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$propertyId': {
      id: '/_layout/$propertyId'
      path: '/$propertyId'
      fullPath: '/$propertyId'
      preLoaderRoute: typeof LayoutPropertyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_protected/favourites': {
      id: '/_layout/_protected/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof LayoutProtectedFavouritesRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_admin/admin': {
      id: '/_layout/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutProtectedRouteChildren {
  LayoutProtectedFavouritesRoute: typeof LayoutProtectedFavouritesRoute
}

const LayoutProtectedRouteChildren: LayoutProtectedRouteChildren = {
  LayoutProtectedFavouritesRoute: LayoutProtectedFavouritesRoute,
}

const LayoutProtectedRouteWithChildren = LayoutProtectedRoute._addFileChildren(
  LayoutProtectedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutPropertyIdRoute: typeof LayoutPropertyIdRoute
  LayoutProtectedRoute: typeof LayoutProtectedRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminAdminRoute: typeof LayoutAdminAdminRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutPropertyIdRoute: LayoutPropertyIdRoute,
  LayoutProtectedRoute: LayoutProtectedRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminAdminRoute: LayoutAdminAdminRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
